name: Combined CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  combined-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 21f3001880@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: prime-cache-471bc95
        id: prime-cache-471bc95
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-471bc95
          restore-keys: cache-471bc95

      - name: Print Cache Result
        run: |
          if [ "${{ steps.prime-cache-471bc95.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi
