name: Daily Repository Update

on:
  schedule:
    - cron: "40 13 * * *"   # Runs daily at 7:10 PM IST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Update timestamp file (includes 21f3001880@ds.study.iitm.ac.in)
        run: |
          echo "Last Auto Update: $(date -u)" > last_update.txt

      - name: Configure Git User
        run: |
          git config user.name "DevSync Bot"
          git config user.email "21f3001880@ds.study.iitm.ac.in"

      - name: Commit Changes
        run: |
          git add last_update.txt
          git commit -m "Automated daily update: $(date -u)"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
