name: Combined CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 21f3001880@ds.study.iitm.ac.in
        run: echo "Hello, world!"

  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: prime-cache-471bc95
        id: prime-cache-471bc95  # <--- this ID is important
        uses: actions/cache@v4
        with:
          path: ~/.npm   # or your dependency path
          key: cache-471bc95
          restore-keys: cache-471bc95

      - name: Print Cache Result
        run: echo "Cache step result: ${{ steps.prime-cache-471bc95.outcome }}"
